### ISSUE TITLE
error on all-to-all

### ISSUE THREAD

**Issue by ll6611** [laszukdawid/pystan-kuramoto#1]
Hi, laszukdawid, 
I met an error when running the model of all-to-all. The following is it.
The first error is missing file model.pkl
The second error "distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed "
is believed following the first error.
I am a newbie about this, would you please help me ?

x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Traceback (most recent call last):
  File "kuramoto.py", line 82, in <module>
    model = pickle.load(open(model_file_name, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kuramoto.py", line 87, in <module>
    model = pystan.StanModel(model_code=ocode, verbose=True)
  File "/home/lilan/.local/lib/python3.6/site-packages/pystan/model.py", line 378, in __init__
    build_extension.run()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 4

**Comment by laszukdawid** [comment]
Hi @ll6611,

Thanks for the interest in this code. It's been a long time since I used anything with Stan so it required memory refresh :)

Regarding the missing file:
That's intentional. If you take a look at the code [here](https://github.com/laszukdawid/pystan-kuramoto/blob/master/all-to-all/kuramoto.py#L81-L92), it does `try...except` on opening file. If there is a file it just reads the model to save on computation, otherwise, it'll create. It's Ok not to have that file; it'll be created.

Regarding the second error - unfortunately, that's beyond me. It's not due to this package but rather a general system setting so searching through Google/Duckduckgo/Ecosia should help.
To get you somewhere, based on the logs it seems that your gcc compiler is incompatible with whatever you are trying to run and that's most likely the (Py)Stan. I'd suggest starting with updating their versions. On the Ubuntu that'd be something like
```sudo apt-get update && sudo apt-get install build-essentials python-dev``` and ```pip install pystan```.

(Package `build-essentials` contains the latest versions of the necessary compilers.)

Hope this helped!

**Comment by laszukdawid** [comment]
I've also included the **requirements.txt** which has the required packages for the pystan-kuramoto.
